[package]
name = "tulip"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
crossbeam-utils = "0.8.5"
fxhash = "0.2.1"
